import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <div className="flex flex-col min-h-screen">
        <Header/>
        <main className="flex-1">{children}</main>
        <footer className="bg-gray-900 text-white p-4">
          <p>© 2023 Your Company. All rights reserved.</p>
        </footer>
      </div>
    </ClerkProvider>
  );
}
